# Use root/example as user/password credentials

version: '3.9'

services:
  mysqldb:
    platform: linux/amd64
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'erp'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'eyram2020'
      MYSQL_ROOT_PASSWORD: 'eyram2020'
    ports:
      - '3307:3306'
    volumes:
      - mysql:/var/lib/mysql

  discovery-server:
    image: peterado/tresosoft:discovery-server
    container_name: discovery-server
    ports:
      - '8762:8762'

  api-gateway:
    image: peterado/tresosoft:api-gateway
    container_name: api-gateway
    environment:
      - eureka.client.service-url.defaultZone=http://discovery-server:8762/eureka/
      - JAVA_OPTS=-XX:MaxRAM=350m
    depends_on:
      - discovery-server
    ports:
      - '8084:8084'

  configuration-server:
    image: peterado/tresosoft:configuration-server
    container_name: configuration-server
    environment:
      - spring.cloud.config.server.git.uri=https://github.com/Peterery21/config-tresorerie.git
      - spring.cloud.config.server.git.username=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
      - spring.cloud.config.server.git.password=
      - eureka.client.service-url.defaultZone=http://discovery-server:8762/eureka/
      - spring.datasource.url=jdbc:mysql://mysqldb:3307/erp
      - JAVA_OPTS=-XX:MaxRAM=350m
    depends_on:
      - discovery-server
      - mysqldb
  #    ports:
  #      - '8888:8888'

  utilisateur-service:
    image: peterado/tresosoft:utilisateur-service
    container_name: utilisateur-service
    environment:
      - spring.cloud.config.uri=http://configuration-server:8888
      - JAVA_OPTS=-XX:MaxRAM=350m
    depends_on:
      - configuration-server
      - mysqldb

  entite-service:
    image: peterado/tresosoft:entite-service
    container_name: entite-service
    environment:
      - spring.cloud.config.uri=http://configuration-server:8888
      - JAVA_OPTS=-XX:MaxRAM=350m
    depends_on:
      - configuration-server

  compte-service:
    image: peterado/tresosoft:compte-service
    container_name: compte-service
    environment:
      - spring.cloud.config.uri=http://configuration-server:8888
      - JAVA_OPTS=-XX:MaxRAM=350m
    depends_on:
      - configuration-server

  documentcommercial-service:
    image: peterado/tresosoft:documentcommercial-service
    container_name: documentcommercial-service
    environment:
      - spring.cloud.config.uri=http://configuration-server:8888
      - JAVA_OPTS=-XX:MaxRAM=350m
    depends_on:
      - configuration-server

  transaction-service:
    image: peterado/tresosoft:transaction-service
    container_name: transaction-service
    environment:
      - spring.cloud.config.uri=http://configuration-server:8888
      - JAVA_OPTS=-XX:MaxRAM=350m
    depends_on:
      - configuration-server

  fileupload-service:
    image: peterado/tresosoft:fileupload-service
    container_name: fileupload-service
    environment:
      - spring.cloud.config.uri=http://configuration-server:8888
      - JAVA_OPTS=-XX:MaxRAM=350m
    depends_on:
      - configuration-server
    volumes:
      - .upload:/upload

  notification-service:
    image: peterado/tresosoft:notification-service
    container_name: notification-service
    environment:
      - spring.cloud.config.uri=http://configuration-server:8888
      - JAVA_OPTS=-XX:MaxRAM=350m
    depends_on:
      - configuration-server

  angular:
    image: peterado/tresosoft:angular
    container_name: angular
    ports:
      - '9111:80'
    depends_on:
      - api-gateway

volumes:
  mysql:

networks:
  default:
    driver: bridge